--<ScriptOptions statementTerminator=";"/>
-- version 1.1
-- maintainer: ruifengm@sg.ibm.com

CREATE SCHEMA JENKINS;

CREATE TABLE JENKINS.BRAKEMAN_DEFECT (  
	DEFECT_ID            integer NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE CACHE 20 NO ORDER ) ,
	DEFECT_NUMBER        integer NOT NULL ,
	DEFECT_NAME          varchar(500) NOT NULL  ,
	BUILD                varchar(250) NOT NULL  ,
	FILING_TIMESTAMP     timestamp NOT NULL  ,
	MODIFICATION_TIMES   integer NOT NULL DEFAULT 0 ,
	MODIFICATION_TIMESTAMP timestamp NOT NULL GENERATED ALWAYS FOR EACH ROW ON UPDATE AS ROW CHANGE TIMESTAMP,
	DEFECT_STATUS        varchar(100) NOT NULL  ,
	DEFECT_LINK          varchar(250) NOT NULL  ,
	PROJECT              varchar(100) NOT NULL  ,
	CONSTRAINT PK_BRAKEMAN_DEFECT PRIMARY KEY ( DEFECT_ID )
 );

CREATE TABLE JENKINS.BRAKEMAN_ERROR ( 
	ERROR_ID             integer NOT NULL  ,
	CONSTRAINT PK_BRAKEMAN_ERROR PRIMARY KEY ( ERROR_ID )
 );
 
 CREATE TABLE JENKINS.BERKS_DEFECT (  
	DEFECT_ID            integer NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE CACHE 20 NO ORDER ) ,
	DEFECT_NUMBER        integer NOT NULL ,
	DEFECT_NAME          varchar(500) NOT NULL  ,
	GIT_BRANCH           varchar(100) NOT NULL  ,
	COOKBOOK             varchar(100) NOT NULL  ,
	GIT_PR_LINK          varchar(800)  ,
	FILING_TIMESTAMP     timestamp NOT NULL  ,
	MODIFICATION_TIMES   integer NOT NULL DEFAULT 0 ,
	MODIFICATION_TIMESTAMP timestamp NOT NULL GENERATED ALWAYS FOR EACH ROW ON UPDATE AS ROW CHANGE TIMESTAMP,
	DEFECT_STATUS        varchar(100) NOT NULL  ,
	DEFECT_LINK          varchar(250) NOT NULL  ,
	CONSTRAINT PK_BERKS_DEFECT PRIMARY KEY ( DEFECT_ID )
 );

CREATE TABLE JENKINS.BRAKEMAN_WARNING ( 
	WARNING_ID           integer NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE CACHE 20 NO ORDER ) ,
	WARNING_TYPE         varchar(250) NOT NULL  ,
	FILE_NAME            varchar(250) NOT NULL  ,
	MESSAGE              varchar(5000) NOT NULL  ,
	CONFIDENCE           varchar(50) NOT NULL  ,
	BUILD                varchar(100) NOT NULL  ,
	DEFECT_ID            integer NOT NULL  ,
	CONSTRAINT PK_BRAKEMAN_WARNING PRIMARY KEY ( WARNING_ID )
 );

-- indices
CREATE INDEX JENKINS.IDX_BRAKEMAN_WARNING ON JENKINS.BRAKEMAN_WARNING ( DEFECT_ID );

-- unique constraint
ALTER TABLE JENKINS.BRAKEMAN_DEFECT ADD CONSTRAINT DEFECT_NUMBER_UN UNIQUE ("DEFECT_NUMBER");
ALTER TABLE JENKINS.BERKS_DEFECT ADD CONSTRAINT BERKS_DEFECT_NUMBER_UN UNIQUE ("DEFECT_NUMBER");

-- foreign keys
ALTER TABLE JENKINS.BRAKEMAN_WARNING ADD FOREIGN KEY FK_BRAKEMAN_WARNING ( DEFECT_ID ) REFERENCES JENKINS.BRAKEMAN_DEFECT( DEFECT_ID ) ON DELETE NO ACTION ON UPDATE RESTRICT;

